CREATE TABLE PROVEEDORES (
    ID BIGINT NOT NULL,
    NOMBRE varchar(255),
    FECHA_ALTA varchar(255),
    ID_CLIENTE BIGINT,
    PRIMARY KEY (ID)
);

INSERT INTO PROVEEDORES (ID, NOMBRE, FECHA_ALTA, ID_CLIENTE) VALUES (1,'Coca-cola', '11/12/2020', 5);
INSERT INTO PROVEEDORES (ID, NOMBRE, FECHA_ALTA, ID_CLIENTE) VALUES (2,'Pepsi', '12/12/2020', 5);
INSERT INTO PROVEEDORES (ID, NOMBRE, FECHA_ALTA, ID_CLIENTE) VALUES (3,'Redbull', '13/12/2020', 6);